# Hologram config

# The directory containing the source files to parse
source: ../sass/components-hologram

# The directory that hologram will build to
destination: ../build/styleguide-hologram

# Hologram theme
documentation_assets: ../bower_components/Cortana
custom_markdown: ../bower_components/Cortana/CortanaMarkdownRenderer.rb

dependencies:


# Mark which category should be the index page
# Alternatively, you may have an index.md in the documentation assets
# folder instead of specifying this config.
# index: index

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - ../main.css

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'http://code.jquery.com/jquery-1.10.2.min.js'

# String who is used to split the category name and create category wrapper
name_scope: ' - '
